### ISSUE TITLE
Meta-issue: Revision of FunctionSurj

### ISSUE THREAD

**Issue by TentativeConvert** [hhu-adam/Robo#55]
I collect here things that need to happen in FunctionSurj

- [ ] add zeroeth level to introduce notation f : A → B for functions or try make this notation visible in level 1 – see  https://github.com/hhu-adam/Robo/issues/54#issue-2390911564
- [ ] decide whether we can implement polyrith, and if not, whether we want to keep manual linear_combination in [level 6](https://github.com/hhu-adam/Robo/blob/f086cf9c78fa15d50e3494b87b755f0308619263/Game/Levels/FunctionSurj/L06_RightInverse.lean); if not: delete/replace this level
- [ ] swap levels 4 (right inverse) and 5 (left inverse):  the fact that left inverse is defined in terms of right inverse is already obvious in current level 4 to anyone who cares to `unfold` the definition
- [ ] add hints to levels 4, 6, … ? …
- [ ] Marcus: rewrite story

**Comment by TentativeConvert** [comment]
(The whole function complex has been completely reorganised by now.)
